cp ../data/src_food/training/0_0.jpg ../data/food-training-sample
cp ../data/src_food/training/0_116.jpg ../data/food-training-sample
cp ../data/src_food/training/0_122.jpg ../data/food-training-sample
cp ../data/src_food/training/0_123.jpg ../data/food-training-sample
cp ../data/src_food/training/0_125.jpg ../data/food-training-sample
cp ../data/src_food/training/0_130.jpg ../data/food-training-sample
cp ../data/src_food/training/0_136.jpg ../data/food-training-sample
cp ../data/src_food/training/0_14.jpg ../data/food-training-sample
cp ../data/src_food/training/0_150.jpg ../data/food-training-sample
cp ../data/src_food/training/0_161.jpg ../data/food-training-sample
cp ../data/src_food/training/0_170.jpg ../data/food-training-sample
cp ../data/src_food/training/0_202.jpg ../data/food-training-sample
cp ../data/src_food/training/0_210.jpg ../data/food-training-sample
cp ../data/src_food/training/0_212.jpg ../data/food-training-sample
cp ../data/src_food/training/0_213.jpg ../data/food-training-sample
cp ../data/src_food/training/0_220.jpg ../data/food-training-sample
cp ../data/src_food/training/0_221.jpg ../data/food-training-sample
cp ../data/src_food/training/0_234.jpg ../data/food-training-sample
cp ../data/src_food/training/0_265.jpg ../data/food-training-sample
cp ../data/src_food/training/0_266.jpg ../data/food-training-sample
cp ../data/src_food/training/0_271.jpg ../data/food-training-sample
cp ../data/src_food/training/0_274.jpg ../data/food-training-sample
cp ../data/src_food/training/0_281.jpg ../data/food-training-sample
cp ../data/src_food/training/0_28.jpg ../data/food-training-sample
cp ../data/src_food/training/0_299.jpg ../data/food-training-sample
cp ../data/src_food/training/0_304.jpg ../data/food-training-sample
cp ../data/src_food/training/0_309.jpg ../data/food-training-sample
cp ../data/src_food/training/0_315.jpg ../data/food-training-sample
cp ../data/src_food/training/0_352.jpg ../data/food-training-sample
cp ../data/src_food/training/0_357.jpg ../data/food-training-sample
cp ../data/src_food/training/0_374.jpg ../data/food-training-sample
cp ../data/src_food/training/0_379.jpg ../data/food-training-sample
cp ../data/src_food/training/0_386.jpg ../data/food-training-sample
cp ../data/src_food/training/0_392.jpg ../data/food-training-sample
cp ../data/src_food/training/0_394.jpg ../data/food-training-sample
cp ../data/src_food/training/0_3.jpg ../data/food-training-sample
cp ../data/src_food/training/0_408.jpg ../data/food-training-sample
cp ../data/src_food/training/0_411.jpg ../data/food-training-sample
cp ../data/src_food/training/0_414.jpg ../data/food-training-sample
cp ../data/src_food/training/0_416.jpg ../data/food-training-sample
cp ../data/src_food/training/0_423.jpg ../data/food-training-sample
cp ../data/src_food/training/0_437.jpg ../data/food-training-sample
cp ../data/src_food/training/0_450.jpg ../data/food-training-sample
cp ../data/src_food/training/0_468.jpg ../data/food-training-sample
cp ../data/src_food/training/0_47.jpg ../data/food-training-sample
cp ../data/src_food/training/0_484.jpg ../data/food-training-sample
cp ../data/src_food/training/0_48.jpg ../data/food-training-sample
cp ../data/src_food/training/0_496.jpg ../data/food-training-sample
cp ../data/src_food/training/0_504.jpg ../data/food-training-sample
cp ../data/src_food/training/0_513.jpg ../data/food-training-sample
cp ../data/src_food/training/0_514.jpg ../data/food-training-sample
cp ../data/src_food/training/0_518.jpg ../data/food-training-sample
cp ../data/src_food/training/0_526.jpg ../data/food-training-sample
cp ../data/src_food/training/0_528.jpg ../data/food-training-sample
cp ../data/src_food/training/0_548.jpg ../data/food-training-sample
cp ../data/src_food/training/0_579.jpg ../data/food-training-sample
cp ../data/src_food/training/0_588.jpg ../data/food-training-sample
cp ../data/src_food/training/0_591.jpg ../data/food-training-sample
cp ../data/src_food/training/0_596.jpg ../data/food-training-sample
cp ../data/src_food/training/0_599.jpg ../data/food-training-sample
cp ../data/src_food/training/0_601.jpg ../data/food-training-sample
cp ../data/src_food/training/0_602.jpg ../data/food-training-sample
cp ../data/src_food/training/0_604.jpg ../data/food-training-sample
cp ../data/src_food/training/0_60.jpg ../data/food-training-sample
cp ../data/src_food/training/0_621.jpg ../data/food-training-sample
cp ../data/src_food/training/0_626.jpg ../data/food-training-sample
cp ../data/src_food/training/0_627.jpg ../data/food-training-sample
cp ../data/src_food/training/0_650.jpg ../data/food-training-sample
cp ../data/src_food/training/0_656.jpg ../data/food-training-sample
cp ../data/src_food/training/0_668.jpg ../data/food-training-sample
cp ../data/src_food/training/0_673.jpg ../data/food-training-sample
cp ../data/src_food/training/0_689.jpg ../data/food-training-sample
cp ../data/src_food/training/0_690.jpg ../data/food-training-sample
cp ../data/src_food/training/0_695.jpg ../data/food-training-sample
cp ../data/src_food/training/0_697.jpg ../data/food-training-sample
cp ../data/src_food/training/0_709.jpg ../data/food-training-sample
cp ../data/src_food/training/0_714.jpg ../data/food-training-sample
cp ../data/src_food/training/0_733.jpg ../data/food-training-sample
cp ../data/src_food/training/0_744.jpg ../data/food-training-sample
cp ../data/src_food/training/0_757.jpg ../data/food-training-sample
cp ../data/src_food/training/0_758.jpg ../data/food-training-sample
cp ../data/src_food/training/0_762.jpg ../data/food-training-sample
cp ../data/src_food/training/0_777.jpg ../data/food-training-sample
cp ../data/src_food/training/0_783.jpg ../data/food-training-sample
cp ../data/src_food/training/0_784.jpg ../data/food-training-sample
cp ../data/src_food/training/0_808.jpg ../data/food-training-sample
cp ../data/src_food/training/0_815.jpg ../data/food-training-sample
cp ../data/src_food/training/0_828.jpg ../data/food-training-sample
cp ../data/src_food/training/0_846.jpg ../data/food-training-sample
cp ../data/src_food/training/0_863.jpg ../data/food-training-sample
cp ../data/src_food/training/0_87.jpg ../data/food-training-sample
cp ../data/src_food/training/0_897.jpg ../data/food-training-sample
cp ../data/src_food/training/0_8.jpg ../data/food-training-sample
cp ../data/src_food/training/0_911.jpg ../data/food-training-sample
cp ../data/src_food/training/0_951.jpg ../data/food-training-sample
cp ../data/src_food/training/0_962.jpg ../data/food-training-sample
cp ../data/src_food/training/0_967.jpg ../data/food-training-sample
cp ../data/src_food/training/0_970.jpg ../data/food-training-sample
cp ../data/src_food/training/0_97.jpg ../data/food-training-sample
cp ../data/src_food/training/0_981.jpg ../data/food-training-sample
cp ../data/src_food/training/1_0.jpg ../data/food-training-sample
cp ../data/src_food/training/1_102.jpg ../data/food-training-sample
cp ../data/src_food/training/1_103.jpg ../data/food-training-sample
cp ../data/src_food/training/1_104.jpg ../data/food-training-sample
cp ../data/src_food/training/1_105.jpg ../data/food-training-sample
cp ../data/src_food/training/1_108.jpg ../data/food-training-sample
cp ../data/src_food/training/1_10.jpg ../data/food-training-sample
cp ../data/src_food/training/1_119.jpg ../data/food-training-sample
cp ../data/src_food/training/1_11.jpg ../data/food-training-sample
cp ../data/src_food/training/1_122.jpg ../data/food-training-sample
cp ../data/src_food/training/1_12.jpg ../data/food-training-sample
cp ../data/src_food/training/1_131.jpg ../data/food-training-sample
cp ../data/src_food/training/1_138.jpg ../data/food-training-sample
cp ../data/src_food/training/1_13.jpg ../data/food-training-sample
cp ../data/src_food/training/1_14.jpg ../data/food-training-sample
cp ../data/src_food/training/1_150.jpg ../data/food-training-sample
cp ../data/src_food/training/1_153.jpg ../data/food-training-sample
cp ../data/src_food/training/1_158.jpg ../data/food-training-sample
cp ../data/src_food/training/1_161.jpg ../data/food-training-sample
cp ../data/src_food/training/1_172.jpg ../data/food-training-sample
cp ../data/src_food/training/1_174.jpg ../data/food-training-sample
cp ../data/src_food/training/1_175.jpg ../data/food-training-sample
cp ../data/src_food/training/1_180.jpg ../data/food-training-sample
cp ../data/src_food/training/1_181.jpg ../data/food-training-sample
cp ../data/src_food/training/1_186.jpg ../data/food-training-sample
cp ../data/src_food/training/1_189.jpg ../data/food-training-sample
cp ../data/src_food/training/1_190.jpg ../data/food-training-sample
cp ../data/src_food/training/1_195.jpg ../data/food-training-sample
cp ../data/src_food/training/1_1.jpg ../data/food-training-sample
cp ../data/src_food/training/1_201.jpg ../data/food-training-sample
cp ../data/src_food/training/1_204.jpg ../data/food-training-sample
cp ../data/src_food/training/1_205.jpg ../data/food-training-sample
cp ../data/src_food/training/1_211.jpg ../data/food-training-sample
cp ../data/src_food/training/1_220.jpg ../data/food-training-sample
cp ../data/src_food/training/1_225.jpg ../data/food-training-sample
cp ../data/src_food/training/1_235.jpg ../data/food-training-sample
cp ../data/src_food/training/1_237.jpg ../data/food-training-sample
cp ../data/src_food/training/1_245.jpg ../data/food-training-sample
cp ../data/src_food/training/1_250.jpg ../data/food-training-sample
cp ../data/src_food/training/1_258.jpg ../data/food-training-sample
cp ../data/src_food/training/1_261.jpg ../data/food-training-sample
cp ../data/src_food/training/1_264.jpg ../data/food-training-sample
cp ../data/src_food/training/1_267.jpg ../data/food-training-sample
cp ../data/src_food/training/1_268.jpg ../data/food-training-sample
cp ../data/src_food/training/1_277.jpg ../data/food-training-sample
cp ../data/src_food/training/1_285.jpg ../data/food-training-sample
cp ../data/src_food/training/1_287.jpg ../data/food-training-sample
cp ../data/src_food/training/1_289.jpg ../data/food-training-sample
cp ../data/src_food/training/1_290.jpg ../data/food-training-sample
cp ../data/src_food/training/1_297.jpg ../data/food-training-sample
cp ../data/src_food/training/1_29.jpg ../data/food-training-sample
cp ../data/src_food/training/1_304.jpg ../data/food-training-sample
cp ../data/src_food/training/1_307.jpg ../data/food-training-sample
cp ../data/src_food/training/1_30.jpg ../data/food-training-sample
cp ../data/src_food/training/1_310.jpg ../data/food-training-sample
cp ../data/src_food/training/1_311.jpg ../data/food-training-sample
cp ../data/src_food/training/1_314.jpg ../data/food-training-sample
cp ../data/src_food/training/1_324.jpg ../data/food-training-sample
cp ../data/src_food/training/1_327.jpg ../data/food-training-sample
cp ../data/src_food/training/1_332.jpg ../data/food-training-sample
cp ../data/src_food/training/1_339.jpg ../data/food-training-sample
cp ../data/src_food/training/1_33.jpg ../data/food-training-sample
cp ../data/src_food/training/1_340.jpg ../data/food-training-sample
cp ../data/src_food/training/1_344.jpg ../data/food-training-sample
cp ../data/src_food/training/1_351.jpg ../data/food-training-sample
cp ../data/src_food/training/1_352.jpg ../data/food-training-sample
cp ../data/src_food/training/1_357.jpg ../data/food-training-sample
cp ../data/src_food/training/1_377.jpg ../data/food-training-sample
cp ../data/src_food/training/1_385.jpg ../data/food-training-sample
cp ../data/src_food/training/1_38.jpg ../data/food-training-sample
cp ../data/src_food/training/1_391.jpg ../data/food-training-sample
cp ../data/src_food/training/1_395.jpg ../data/food-training-sample
cp ../data/src_food/training/1_401.jpg ../data/food-training-sample
cp ../data/src_food/training/1_402.jpg ../data/food-training-sample
cp ../data/src_food/training/1_403.jpg ../data/food-training-sample
cp ../data/src_food/training/1_404.jpg ../data/food-training-sample
cp ../data/src_food/training/1_405.jpg ../data/food-training-sample
cp ../data/src_food/training/1_406.jpg ../data/food-training-sample
cp ../data/src_food/training/1_407.jpg ../data/food-training-sample
cp ../data/src_food/training/1_421.jpg ../data/food-training-sample
cp ../data/src_food/training/1_423.jpg ../data/food-training-sample
cp ../data/src_food/training/1_424.jpg ../data/food-training-sample
cp ../data/src_food/training/1_42.jpg ../data/food-training-sample
cp ../data/src_food/training/1_46.jpg ../data/food-training-sample
cp ../data/src_food/training/1_49.jpg ../data/food-training-sample
cp ../data/src_food/training/1_52.jpg ../data/food-training-sample
cp ../data/src_food/training/1_53.jpg ../data/food-training-sample
cp ../data/src_food/training/1_58.jpg ../data/food-training-sample
cp ../data/src_food/training/1_5.jpg ../data/food-training-sample
cp ../data/src_food/training/1_70.jpg ../data/food-training-sample
cp ../data/src_food/training/1_72.jpg ../data/food-training-sample
cp ../data/src_food/training/1_73.jpg ../data/food-training-sample
cp ../data/src_food/training/1_75.jpg ../data/food-training-sample
cp ../data/src_food/training/1_85.jpg ../data/food-training-sample
cp ../data/src_food/training/1_86.jpg ../data/food-training-sample
cp ../data/src_food/training/1_88.jpg ../data/food-training-sample
cp ../data/src_food/training/1_90.jpg ../data/food-training-sample
cp ../data/src_food/training/1_92.jpg ../data/food-training-sample
cp ../data/src_food/training/1_95.jpg ../data/food-training-sample
cp ../data/src_food/training/1_99.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1001.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1021.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1027.jpg ../data/food-training-sample
cp ../data/src_food/training/2_103.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1048.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1059.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1062.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1078.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1094.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1100.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1102.jpg ../data/food-training-sample
cp ../data/src_food/training/2_110.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1138.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1176.jpg ../data/food-training-sample
cp ../data/src_food/training/2_118.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1195.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1198.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1223.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1245.jpg ../data/food-training-sample
cp ../data/src_food/training/2_124.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1264.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1270.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1285.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1292.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1302.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1307.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1342.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1365.jpg ../data/food-training-sample
cp ../data/src_food/training/2_137.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1419.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1433.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1434.jpg ../data/food-training-sample
cp ../data/src_food/training/2_143.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1448.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1449.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1458.jpg ../data/food-training-sample
cp ../data/src_food/training/2_1493.jpg ../data/food-training-sample
cp ../data/src_food/training/2_149.jpg ../data/food-training-sample
cp ../data/src_food/training/2_165.jpg ../data/food-training-sample
cp ../data/src_food/training/2_178.jpg ../data/food-training-sample
cp ../data/src_food/training/2_197.jpg ../data/food-training-sample
cp ../data/src_food/training/2_202.jpg ../data/food-training-sample
cp ../data/src_food/training/2_211.jpg ../data/food-training-sample
cp ../data/src_food/training/2_220.jpg ../data/food-training-sample
cp ../data/src_food/training/2_226.jpg ../data/food-training-sample
cp ../data/src_food/training/2_234.jpg ../data/food-training-sample
cp ../data/src_food/training/2_240.jpg ../data/food-training-sample
cp ../data/src_food/training/2_268.jpg ../data/food-training-sample
cp ../data/src_food/training/2_285.jpg ../data/food-training-sample
cp ../data/src_food/training/2_287.jpg ../data/food-training-sample
cp ../data/src_food/training/2_334.jpg ../data/food-training-sample
cp ../data/src_food/training/2_341.jpg ../data/food-training-sample
cp ../data/src_food/training/2_359.jpg ../data/food-training-sample
cp ../data/src_food/training/2_396.jpg ../data/food-training-sample
cp ../data/src_food/training/2_448.jpg ../data/food-training-sample
cp ../data/src_food/training/2_451.jpg ../data/food-training-sample
cp ../data/src_food/training/2_453.jpg ../data/food-training-sample
cp ../data/src_food/training/2_490.jpg ../data/food-training-sample
cp ../data/src_food/training/2_525.jpg ../data/food-training-sample
cp ../data/src_food/training/2_528.jpg ../data/food-training-sample
cp ../data/src_food/training/2_546.jpg ../data/food-training-sample
cp ../data/src_food/training/2_586.jpg ../data/food-training-sample
cp ../data/src_food/training/2_601.jpg ../data/food-training-sample
cp ../data/src_food/training/2_609.jpg ../data/food-training-sample
cp ../data/src_food/training/2_61.jpg ../data/food-training-sample
cp ../data/src_food/training/2_642.jpg ../data/food-training-sample
cp ../data/src_food/training/2_651.jpg ../data/food-training-sample
cp ../data/src_food/training/2_653.jpg ../data/food-training-sample
cp ../data/src_food/training/2_659.jpg ../data/food-training-sample
cp ../data/src_food/training/2_662.jpg ../data/food-training-sample
cp ../data/src_food/training/2_672.jpg ../data/food-training-sample
cp ../data/src_food/training/2_673.jpg ../data/food-training-sample
cp ../data/src_food/training/2_697.jpg ../data/food-training-sample
cp ../data/src_food/training/2_727.jpg ../data/food-training-sample
cp ../data/src_food/training/2_735.jpg ../data/food-training-sample
cp ../data/src_food/training/2_73.jpg ../data/food-training-sample
cp ../data/src_food/training/2_741.jpg ../data/food-training-sample
cp ../data/src_food/training/2_745.jpg ../data/food-training-sample
cp ../data/src_food/training/2_746.jpg ../data/food-training-sample
cp ../data/src_food/training/2_749.jpg ../data/food-training-sample
cp ../data/src_food/training/2_756.jpg ../data/food-training-sample
cp ../data/src_food/training/2_76.jpg ../data/food-training-sample
cp ../data/src_food/training/2_778.jpg ../data/food-training-sample
cp ../data/src_food/training/2_786.jpg ../data/food-training-sample
cp ../data/src_food/training/2_787.jpg ../data/food-training-sample
cp ../data/src_food/training/2_78.jpg ../data/food-training-sample
cp ../data/src_food/training/2_801.jpg ../data/food-training-sample
cp ../data/src_food/training/2_802.jpg ../data/food-training-sample
cp ../data/src_food/training/2_811.jpg ../data/food-training-sample
cp ../data/src_food/training/2_81.jpg ../data/food-training-sample
cp ../data/src_food/training/2_827.jpg ../data/food-training-sample
cp ../data/src_food/training/2_841.jpg ../data/food-training-sample
cp ../data/src_food/training/2_872.jpg ../data/food-training-sample
cp ../data/src_food/training/2_882.jpg ../data/food-training-sample
cp ../data/src_food/training/2_887.jpg ../data/food-training-sample
cp ../data/src_food/training/2_906.jpg ../data/food-training-sample
cp ../data/src_food/training/2_91.jpg ../data/food-training-sample
cp ../data/src_food/training/2_926.jpg ../data/food-training-sample
cp ../data/src_food/training/2_93.jpg ../data/food-training-sample
cp ../data/src_food/training/2_949.jpg ../data/food-training-sample
cp ../data/src_food/training/3_101.jpg ../data/food-training-sample
cp ../data/src_food/training/3_106.jpg ../data/food-training-sample
cp ../data/src_food/training/3_109.jpg ../data/food-training-sample
cp ../data/src_food/training/3_111.jpg ../data/food-training-sample
cp ../data/src_food/training/3_116.jpg ../data/food-training-sample
cp ../data/src_food/training/3_117.jpg ../data/food-training-sample
cp ../data/src_food/training/3_126.jpg ../data/food-training-sample
cp ../data/src_food/training/3_127.jpg ../data/food-training-sample
cp ../data/src_food/training/3_129.jpg ../data/food-training-sample
cp ../data/src_food/training/3_137.jpg ../data/food-training-sample
cp ../data/src_food/training/3_139.jpg ../data/food-training-sample
cp ../data/src_food/training/3_157.jpg ../data/food-training-sample
cp ../data/src_food/training/3_159.jpg ../data/food-training-sample
cp ../data/src_food/training/3_164.jpg ../data/food-training-sample
cp ../data/src_food/training/3_182.jpg ../data/food-training-sample
cp ../data/src_food/training/3_189.jpg ../data/food-training-sample
cp ../data/src_food/training/3_192.jpg ../data/food-training-sample
cp ../data/src_food/training/3_213.jpg ../data/food-training-sample
cp ../data/src_food/training/3_218.jpg ../data/food-training-sample
cp ../data/src_food/training/3_21.jpg ../data/food-training-sample
cp ../data/src_food/training/3_228.jpg ../data/food-training-sample
cp ../data/src_food/training/3_229.jpg ../data/food-training-sample
cp ../data/src_food/training/3_22.jpg ../data/food-training-sample
cp ../data/src_food/training/3_244.jpg ../data/food-training-sample
cp ../data/src_food/training/3_249.jpg ../data/food-training-sample
cp ../data/src_food/training/3_290.jpg ../data/food-training-sample
cp ../data/src_food/training/3_295.jpg ../data/food-training-sample
cp ../data/src_food/training/3_298.jpg ../data/food-training-sample
cp ../data/src_food/training/3_302.jpg ../data/food-training-sample
cp ../data/src_food/training/3_317.jpg ../data/food-training-sample
cp ../data/src_food/training/3_330.jpg ../data/food-training-sample
cp ../data/src_food/training/3_340.jpg ../data/food-training-sample
cp ../data/src_food/training/3_342.jpg ../data/food-training-sample
cp ../data/src_food/training/3_344.jpg ../data/food-training-sample
cp ../data/src_food/training/3_348.jpg ../data/food-training-sample
cp ../data/src_food/training/3_359.jpg ../data/food-training-sample
cp ../data/src_food/training/3_362.jpg ../data/food-training-sample
cp ../data/src_food/training/3_377.jpg ../data/food-training-sample
cp ../data/src_food/training/3_385.jpg ../data/food-training-sample
cp ../data/src_food/training/3_38.jpg ../data/food-training-sample
cp ../data/src_food/training/3_390.jpg ../data/food-training-sample
cp ../data/src_food/training/3_392.jpg ../data/food-training-sample
cp ../data/src_food/training/3_396.jpg ../data/food-training-sample
cp ../data/src_food/training/3_407.jpg ../data/food-training-sample
cp ../data/src_food/training/3_411.jpg ../data/food-training-sample
cp ../data/src_food/training/3_415.jpg ../data/food-training-sample
cp ../data/src_food/training/3_434.jpg ../data/food-training-sample
cp ../data/src_food/training/3_447.jpg ../data/food-training-sample
cp ../data/src_food/training/3_448.jpg ../data/food-training-sample
cp ../data/src_food/training/3_459.jpg ../data/food-training-sample
cp ../data/src_food/training/3_460.jpg ../data/food-training-sample
cp ../data/src_food/training/3_465.jpg ../data/food-training-sample
cp ../data/src_food/training/3_476.jpg ../data/food-training-sample
cp ../data/src_food/training/3_480.jpg ../data/food-training-sample
cp ../data/src_food/training/3_497.jpg ../data/food-training-sample
cp ../data/src_food/training/3_500.jpg ../data/food-training-sample
cp ../data/src_food/training/3_50.jpg ../data/food-training-sample
cp ../data/src_food/training/3_518.jpg ../data/food-training-sample
cp ../data/src_food/training/3_525.jpg ../data/food-training-sample
cp ../data/src_food/training/3_526.jpg ../data/food-training-sample
cp ../data/src_food/training/3_539.jpg ../data/food-training-sample
cp ../data/src_food/training/3_543.jpg ../data/food-training-sample
cp ../data/src_food/training/3_567.jpg ../data/food-training-sample
cp ../data/src_food/training/3_574.jpg ../data/food-training-sample
cp ../data/src_food/training/3_578.jpg ../data/food-training-sample
cp ../data/src_food/training/3_592.jpg ../data/food-training-sample
cp ../data/src_food/training/3_606.jpg ../data/food-training-sample
cp ../data/src_food/training/3_614.jpg ../data/food-training-sample
cp ../data/src_food/training/3_623.jpg ../data/food-training-sample
cp ../data/src_food/training/3_625.jpg ../data/food-training-sample
cp ../data/src_food/training/3_632.jpg ../data/food-training-sample
cp ../data/src_food/training/3_639.jpg ../data/food-training-sample
cp ../data/src_food/training/3_63.jpg ../data/food-training-sample
cp ../data/src_food/training/3_660.jpg ../data/food-training-sample
cp ../data/src_food/training/3_661.jpg ../data/food-training-sample
cp ../data/src_food/training/3_665.jpg ../data/food-training-sample
cp ../data/src_food/training/3_668.jpg ../data/food-training-sample
cp ../data/src_food/training/3_685.jpg ../data/food-training-sample
cp ../data/src_food/training/3_686.jpg ../data/food-training-sample
cp ../data/src_food/training/3_702.jpg ../data/food-training-sample
cp ../data/src_food/training/3_718.jpg ../data/food-training-sample
cp ../data/src_food/training/3_737.jpg ../data/food-training-sample
cp ../data/src_food/training/3_754.jpg ../data/food-training-sample
cp ../data/src_food/training/3_766.jpg ../data/food-training-sample
cp ../data/src_food/training/3_767.jpg ../data/food-training-sample
cp ../data/src_food/training/3_769.jpg ../data/food-training-sample
cp ../data/src_food/training/3_770.jpg ../data/food-training-sample
cp ../data/src_food/training/3_7.jpg ../data/food-training-sample
cp ../data/src_food/training/3_810.jpg ../data/food-training-sample
cp ../data/src_food/training/3_841.jpg ../data/food-training-sample
cp ../data/src_food/training/3_846.jpg ../data/food-training-sample
cp ../data/src_food/training/3_865.jpg ../data/food-training-sample
cp ../data/src_food/training/3_868.jpg ../data/food-training-sample
cp ../data/src_food/training/3_894.jpg ../data/food-training-sample
cp ../data/src_food/training/3_901.jpg ../data/food-training-sample
cp ../data/src_food/training/3_92.jpg ../data/food-training-sample
cp ../data/src_food/training/3_962.jpg ../data/food-training-sample
cp ../data/src_food/training/3_96.jpg ../data/food-training-sample
cp ../data/src_food/training/3_982.jpg ../data/food-training-sample
cp ../data/src_food/training/3_985.jpg ../data/food-training-sample
cp ../data/src_food/training/4_102.jpg ../data/food-training-sample
cp ../data/src_food/training/4_112.jpg ../data/food-training-sample
cp ../data/src_food/training/4_121.jpg ../data/food-training-sample
cp ../data/src_food/training/4_122.jpg ../data/food-training-sample
cp ../data/src_food/training/4_123.jpg ../data/food-training-sample
cp ../data/src_food/training/4_128.jpg ../data/food-training-sample
cp ../data/src_food/training/4_142.jpg ../data/food-training-sample
cp ../data/src_food/training/4_149.jpg ../data/food-training-sample
cp ../data/src_food/training/4_152.jpg ../data/food-training-sample
cp ../data/src_food/training/4_155.jpg ../data/food-training-sample
cp ../data/src_food/training/4_159.jpg ../data/food-training-sample
cp ../data/src_food/training/4_170.jpg ../data/food-training-sample
cp ../data/src_food/training/4_173.jpg ../data/food-training-sample
cp ../data/src_food/training/4_190.jpg ../data/food-training-sample
cp ../data/src_food/training/4_20.jpg ../data/food-training-sample
cp ../data/src_food/training/4_210.jpg ../data/food-training-sample
cp ../data/src_food/training/4_211.jpg ../data/food-training-sample
cp ../data/src_food/training/4_242.jpg ../data/food-training-sample
cp ../data/src_food/training/4_24.jpg ../data/food-training-sample
cp ../data/src_food/training/4_251.jpg ../data/food-training-sample
cp ../data/src_food/training/4_255.jpg ../data/food-training-sample
cp ../data/src_food/training/4_285.jpg ../data/food-training-sample
cp ../data/src_food/training/4_293.jpg ../data/food-training-sample
cp ../data/src_food/training/4_300.jpg ../data/food-training-sample
cp ../data/src_food/training/4_301.jpg ../data/food-training-sample
cp ../data/src_food/training/4_308.jpg ../data/food-training-sample
cp ../data/src_food/training/4_334.jpg ../data/food-training-sample
cp ../data/src_food/training/4_343.jpg ../data/food-training-sample
cp ../data/src_food/training/4_359.jpg ../data/food-training-sample
cp ../data/src_food/training/4_37.jpg ../data/food-training-sample
cp ../data/src_food/training/4_380.jpg ../data/food-training-sample
cp ../data/src_food/training/4_38.jpg ../data/food-training-sample
cp ../data/src_food/training/4_398.jpg ../data/food-training-sample
cp ../data/src_food/training/4_417.jpg ../data/food-training-sample
cp ../data/src_food/training/4_420.jpg ../data/food-training-sample
cp ../data/src_food/training/4_423.jpg ../data/food-training-sample
cp ../data/src_food/training/4_44.jpg ../data/food-training-sample
cp ../data/src_food/training/4_454.jpg ../data/food-training-sample
cp ../data/src_food/training/4_464.jpg ../data/food-training-sample
cp ../data/src_food/training/4_473.jpg ../data/food-training-sample
cp ../data/src_food/training/4_474.jpg ../data/food-training-sample
cp ../data/src_food/training/4_477.jpg ../data/food-training-sample
cp ../data/src_food/training/4_479.jpg ../data/food-training-sample
cp ../data/src_food/training/4_484.jpg ../data/food-training-sample
cp ../data/src_food/training/4_487.jpg ../data/food-training-sample
cp ../data/src_food/training/4_496.jpg ../data/food-training-sample
cp ../data/src_food/training/4_499.jpg ../data/food-training-sample
cp ../data/src_food/training/4_509.jpg ../data/food-training-sample
cp ../data/src_food/training/4_510.jpg ../data/food-training-sample
cp ../data/src_food/training/4_516.jpg ../data/food-training-sample
cp ../data/src_food/training/4_520.jpg ../data/food-training-sample
cp ../data/src_food/training/4_534.jpg ../data/food-training-sample
cp ../data/src_food/training/4_540.jpg ../data/food-training-sample
cp ../data/src_food/training/4_542.jpg ../data/food-training-sample
cp ../data/src_food/training/4_547.jpg ../data/food-training-sample
cp ../data/src_food/training/4_550.jpg ../data/food-training-sample
cp ../data/src_food/training/4_551.jpg ../data/food-training-sample
cp ../data/src_food/training/4_553.jpg ../data/food-training-sample
cp ../data/src_food/training/4_560.jpg ../data/food-training-sample
cp ../data/src_food/training/4_563.jpg ../data/food-training-sample
cp ../data/src_food/training/4_579.jpg ../data/food-training-sample
cp ../data/src_food/training/4_589.jpg ../data/food-training-sample
cp ../data/src_food/training/4_601.jpg ../data/food-training-sample
cp ../data/src_food/training/4_604.jpg ../data/food-training-sample
cp ../data/src_food/training/4_613.jpg ../data/food-training-sample
cp ../data/src_food/training/4_621.jpg ../data/food-training-sample
cp ../data/src_food/training/4_628.jpg ../data/food-training-sample
cp ../data/src_food/training/4_635.jpg ../data/food-training-sample
cp ../data/src_food/training/4_648.jpg ../data/food-training-sample
cp ../data/src_food/training/4_64.jpg ../data/food-training-sample
cp ../data/src_food/training/4_667.jpg ../data/food-training-sample
cp ../data/src_food/training/4_675.jpg ../data/food-training-sample
cp ../data/src_food/training/4_677.jpg ../data/food-training-sample
cp ../data/src_food/training/4_679.jpg ../data/food-training-sample
cp ../data/src_food/training/4_682.jpg ../data/food-training-sample
cp ../data/src_food/training/4_693.jpg ../data/food-training-sample
cp ../data/src_food/training/4_695.jpg ../data/food-training-sample
cp ../data/src_food/training/4_69.jpg ../data/food-training-sample
cp ../data/src_food/training/4_704.jpg ../data/food-training-sample
cp ../data/src_food/training/4_715.jpg ../data/food-training-sample
cp ../data/src_food/training/4_71.jpg ../data/food-training-sample
cp ../data/src_food/training/4_728.jpg ../data/food-training-sample
cp ../data/src_food/training/4_738.jpg ../data/food-training-sample
cp ../data/src_food/training/4_741.jpg ../data/food-training-sample
cp ../data/src_food/training/4_744.jpg ../data/food-training-sample
cp ../data/src_food/training/4_749.jpg ../data/food-training-sample
cp ../data/src_food/training/4_760.jpg ../data/food-training-sample
cp ../data/src_food/training/4_766.jpg ../data/food-training-sample
cp ../data/src_food/training/4_76.jpg ../data/food-training-sample
cp ../data/src_food/training/4_80.jpg ../data/food-training-sample
cp ../data/src_food/training/4_814.jpg ../data/food-training-sample
cp ../data/src_food/training/4_830.jpg ../data/food-training-sample
cp ../data/src_food/training/4_831.jpg ../data/food-training-sample
cp ../data/src_food/training/4_833.jpg ../data/food-training-sample
cp ../data/src_food/training/4_835.jpg ../data/food-training-sample
cp ../data/src_food/training/4_83.jpg ../data/food-training-sample
cp ../data/src_food/training/4_843.jpg ../data/food-training-sample
cp ../data/src_food/training/4_84.jpg ../data/food-training-sample
cp ../data/src_food/training/4_86.jpg ../data/food-training-sample
cp ../data/src_food/training/4_95.jpg ../data/food-training-sample
cp ../data/src_food/training/5_1009.jpg ../data/food-training-sample
cp ../data/src_food/training/5_100.jpg ../data/food-training-sample
cp ../data/src_food/training/5_1022.jpg ../data/food-training-sample
cp ../data/src_food/training/5_1055.jpg ../data/food-training-sample
cp ../data/src_food/training/5_1065.jpg ../data/food-training-sample
cp ../data/src_food/training/5_1075.jpg ../data/food-training-sample
cp ../data/src_food/training/5_1080.jpg ../data/food-training-sample
cp ../data/src_food/training/5_1082.jpg ../data/food-training-sample
cp ../data/src_food/training/5_1090.jpg ../data/food-training-sample
cp ../data/src_food/training/5_1104.jpg ../data/food-training-sample
cp ../data/src_food/training/5_1108.jpg ../data/food-training-sample
cp ../data/src_food/training/5_1109.jpg ../data/food-training-sample
cp ../data/src_food/training/5_1126.jpg ../data/food-training-sample
cp ../data/src_food/training/5_1137.jpg ../data/food-training-sample
cp ../data/src_food/training/5_1158.jpg ../data/food-training-sample
cp ../data/src_food/training/5_1166.jpg ../data/food-training-sample
cp ../data/src_food/training/5_1178.jpg ../data/food-training-sample
cp ../data/src_food/training/5_1216.jpg ../data/food-training-sample
cp ../data/src_food/training/5_1219.jpg ../data/food-training-sample
cp ../data/src_food/training/5_1221.jpg ../data/food-training-sample
cp ../data/src_food/training/5_1232.jpg ../data/food-training-sample
cp ../data/src_food/training/5_1245.jpg ../data/food-training-sample
cp ../data/src_food/training/5_1247.jpg ../data/food-training-sample
cp ../data/src_food/training/5_1250.jpg ../data/food-training-sample
cp ../data/src_food/training/5_1260.jpg ../data/food-training-sample
cp ../data/src_food/training/5_1274.jpg ../data/food-training-sample
cp ../data/src_food/training/5_1276.jpg ../data/food-training-sample
cp ../data/src_food/training/5_1277.jpg ../data/food-training-sample
cp ../data/src_food/training/5_1298.jpg ../data/food-training-sample
cp ../data/src_food/training/5_1318.jpg ../data/food-training-sample
cp ../data/src_food/training/5_134.jpg ../data/food-training-sample
cp ../data/src_food/training/5_145.jpg ../data/food-training-sample
cp ../data/src_food/training/5_154.jpg ../data/food-training-sample
cp ../data/src_food/training/5_163.jpg ../data/food-training-sample
cp ../data/src_food/training/5_176.jpg ../data/food-training-sample
cp ../data/src_food/training/5_181.jpg ../data/food-training-sample
cp ../data/src_food/training/5_184.jpg ../data/food-training-sample
cp ../data/src_food/training/5_186.jpg ../data/food-training-sample
cp ../data/src_food/training/5_188.jpg ../data/food-training-sample
cp ../data/src_food/training/5_18.jpg ../data/food-training-sample
cp ../data/src_food/training/5_209.jpg ../data/food-training-sample
cp ../data/src_food/training/5_214.jpg ../data/food-training-sample
cp ../data/src_food/training/5_23.jpg ../data/food-training-sample
cp ../data/src_food/training/5_249.jpg ../data/food-training-sample
cp ../data/src_food/training/5_250.jpg ../data/food-training-sample
cp ../data/src_food/training/5_257.jpg ../data/food-training-sample
cp ../data/src_food/training/5_267.jpg ../data/food-training-sample
cp ../data/src_food/training/5_273.jpg ../data/food-training-sample
cp ../data/src_food/training/5_289.jpg ../data/food-training-sample
cp ../data/src_food/training/5_296.jpg ../data/food-training-sample
cp ../data/src_food/training/5_298.jpg ../data/food-training-sample
cp ../data/src_food/training/5_307.jpg ../data/food-training-sample
cp ../data/src_food/training/5_315.jpg ../data/food-training-sample
cp ../data/src_food/training/5_374.jpg ../data/food-training-sample
cp ../data/src_food/training/5_376.jpg ../data/food-training-sample
cp ../data/src_food/training/5_37.jpg ../data/food-training-sample
cp ../data/src_food/training/5_3.jpg ../data/food-training-sample
cp ../data/src_food/training/5_409.jpg ../data/food-training-sample
cp ../data/src_food/training/5_424.jpg ../data/food-training-sample
cp ../data/src_food/training/5_435.jpg ../data/food-training-sample
cp ../data/src_food/training/5_439.jpg ../data/food-training-sample
cp ../data/src_food/training/5_467.jpg ../data/food-training-sample
cp ../data/src_food/training/5_46.jpg ../data/food-training-sample
cp ../data/src_food/training/5_477.jpg ../data/food-training-sample
cp ../data/src_food/training/5_484.jpg ../data/food-training-sample
cp ../data/src_food/training/5_502.jpg ../data/food-training-sample
cp ../data/src_food/training/5_505.jpg ../data/food-training-sample
cp ../data/src_food/training/5_510.jpg ../data/food-training-sample
cp ../data/src_food/training/5_515.jpg ../data/food-training-sample
cp ../data/src_food/training/5_518.jpg ../data/food-training-sample
cp ../data/src_food/training/5_520.jpg ../data/food-training-sample
cp ../data/src_food/training/5_527.jpg ../data/food-training-sample
cp ../data/src_food/training/5_564.jpg ../data/food-training-sample
cp ../data/src_food/training/5_565.jpg ../data/food-training-sample
cp ../data/src_food/training/5_59.jpg ../data/food-training-sample
cp ../data/src_food/training/5_605.jpg ../data/food-training-sample
cp ../data/src_food/training/5_647.jpg ../data/food-training-sample
cp ../data/src_food/training/5_663.jpg ../data/food-training-sample
cp ../data/src_food/training/5_667.jpg ../data/food-training-sample
cp ../data/src_food/training/5_678.jpg ../data/food-training-sample
cp ../data/src_food/training/5_736.jpg ../data/food-training-sample
cp ../data/src_food/training/5_738.jpg ../data/food-training-sample
cp ../data/src_food/training/5_742.jpg ../data/food-training-sample
cp ../data/src_food/training/5_744.jpg ../data/food-training-sample
cp ../data/src_food/training/5_74.jpg ../data/food-training-sample
cp ../data/src_food/training/5_757.jpg ../data/food-training-sample
cp ../data/src_food/training/5_765.jpg ../data/food-training-sample
cp ../data/src_food/training/5_790.jpg ../data/food-training-sample
cp ../data/src_food/training/5_803.jpg ../data/food-training-sample
cp ../data/src_food/training/5_811.jpg ../data/food-training-sample
cp ../data/src_food/training/5_813.jpg ../data/food-training-sample
cp ../data/src_food/training/5_819.jpg ../data/food-training-sample
cp ../data/src_food/training/5_875.jpg ../data/food-training-sample
cp ../data/src_food/training/5_876.jpg ../data/food-training-sample
cp ../data/src_food/training/5_888.jpg ../data/food-training-sample
cp ../data/src_food/training/5_89.jpg ../data/food-training-sample
cp ../data/src_food/training/5_905.jpg ../data/food-training-sample
cp ../data/src_food/training/5_907.jpg ../data/food-training-sample
cp ../data/src_food/training/5_955.jpg ../data/food-training-sample
cp ../data/src_food/training/5_992.jpg ../data/food-training-sample
cp ../data/src_food/training/6_0.jpg ../data/food-training-sample
cp ../data/src_food/training/6_101.jpg ../data/food-training-sample
cp ../data/src_food/training/6_109.jpg ../data/food-training-sample
cp ../data/src_food/training/6_113.jpg ../data/food-training-sample
cp ../data/src_food/training/6_114.jpg ../data/food-training-sample
cp ../data/src_food/training/6_116.jpg ../data/food-training-sample
cp ../data/src_food/training/6_118.jpg ../data/food-training-sample
cp ../data/src_food/training/6_121.jpg ../data/food-training-sample
cp ../data/src_food/training/6_122.jpg ../data/food-training-sample
cp ../data/src_food/training/6_129.jpg ../data/food-training-sample
cp ../data/src_food/training/6_131.jpg ../data/food-training-sample
cp ../data/src_food/training/6_132.jpg ../data/food-training-sample
cp ../data/src_food/training/6_135.jpg ../data/food-training-sample
cp ../data/src_food/training/6_136.jpg ../data/food-training-sample
cp ../data/src_food/training/6_148.jpg ../data/food-training-sample
cp ../data/src_food/training/6_152.jpg ../data/food-training-sample
cp ../data/src_food/training/6_162.jpg ../data/food-training-sample
cp ../data/src_food/training/6_163.jpg ../data/food-training-sample
cp ../data/src_food/training/6_172.jpg ../data/food-training-sample
cp ../data/src_food/training/6_178.jpg ../data/food-training-sample
cp ../data/src_food/training/6_189.jpg ../data/food-training-sample
cp ../data/src_food/training/6_18.jpg ../data/food-training-sample
cp ../data/src_food/training/6_190.jpg ../data/food-training-sample
cp ../data/src_food/training/6_191.jpg ../data/food-training-sample
cp ../data/src_food/training/6_201.jpg ../data/food-training-sample
cp ../data/src_food/training/6_204.jpg ../data/food-training-sample
cp ../data/src_food/training/6_209.jpg ../data/food-training-sample
cp ../data/src_food/training/6_217.jpg ../data/food-training-sample
cp ../data/src_food/training/6_220.jpg ../data/food-training-sample
cp ../data/src_food/training/6_221.jpg ../data/food-training-sample
cp ../data/src_food/training/6_228.jpg ../data/food-training-sample
cp ../data/src_food/training/6_229.jpg ../data/food-training-sample
cp ../data/src_food/training/6_22.jpg ../data/food-training-sample
cp ../data/src_food/training/6_230.jpg ../data/food-training-sample
cp ../data/src_food/training/6_231.jpg ../data/food-training-sample
cp ../data/src_food/training/6_232.jpg ../data/food-training-sample
cp ../data/src_food/training/6_242.jpg ../data/food-training-sample
cp ../data/src_food/training/6_244.jpg ../data/food-training-sample
cp ../data/src_food/training/6_24.jpg ../data/food-training-sample
cp ../data/src_food/training/6_250.jpg ../data/food-training-sample
cp ../data/src_food/training/6_255.jpg ../data/food-training-sample
cp ../data/src_food/training/6_263.jpg ../data/food-training-sample
cp ../data/src_food/training/6_264.jpg ../data/food-training-sample
cp ../data/src_food/training/6_266.jpg ../data/food-training-sample
cp ../data/src_food/training/6_269.jpg ../data/food-training-sample
cp ../data/src_food/training/6_273.jpg ../data/food-training-sample
cp ../data/src_food/training/6_274.jpg ../data/food-training-sample
cp ../data/src_food/training/6_286.jpg ../data/food-training-sample
cp ../data/src_food/training/6_287.jpg ../data/food-training-sample
cp ../data/src_food/training/6_288.jpg ../data/food-training-sample
cp ../data/src_food/training/6_289.jpg ../data/food-training-sample
cp ../data/src_food/training/6_28.jpg ../data/food-training-sample
cp ../data/src_food/training/6_293.jpg ../data/food-training-sample
cp ../data/src_food/training/6_295.jpg ../data/food-training-sample
cp ../data/src_food/training/6_299.jpg ../data/food-training-sample
cp ../data/src_food/training/6_307.jpg ../data/food-training-sample
cp ../data/src_food/training/6_316.jpg ../data/food-training-sample
cp ../data/src_food/training/6_31.jpg ../data/food-training-sample
cp ../data/src_food/training/6_320.jpg ../data/food-training-sample
cp ../data/src_food/training/6_322.jpg ../data/food-training-sample
cp ../data/src_food/training/6_326.jpg ../data/food-training-sample
cp ../data/src_food/training/6_333.jpg ../data/food-training-sample
cp ../data/src_food/training/6_341.jpg ../data/food-training-sample
cp ../data/src_food/training/6_344.jpg ../data/food-training-sample
cp ../data/src_food/training/6_347.jpg ../data/food-training-sample
cp ../data/src_food/training/6_352.jpg ../data/food-training-sample
cp ../data/src_food/training/6_353.jpg ../data/food-training-sample
cp ../data/src_food/training/6_359.jpg ../data/food-training-sample
cp ../data/src_food/training/6_362.jpg ../data/food-training-sample
cp ../data/src_food/training/6_364.jpg ../data/food-training-sample
cp ../data/src_food/training/6_365.jpg ../data/food-training-sample
cp ../data/src_food/training/6_367.jpg ../data/food-training-sample
cp ../data/src_food/training/6_369.jpg ../data/food-training-sample
cp ../data/src_food/training/6_372.jpg ../data/food-training-sample
cp ../data/src_food/training/6_376.jpg ../data/food-training-sample
cp ../data/src_food/training/6_37.jpg ../data/food-training-sample
cp ../data/src_food/training/6_385.jpg ../data/food-training-sample
cp ../data/src_food/training/6_387.jpg ../data/food-training-sample
cp ../data/src_food/training/6_399.jpg ../data/food-training-sample
cp ../data/src_food/training/6_410.jpg ../data/food-training-sample
cp ../data/src_food/training/6_414.jpg ../data/food-training-sample
cp ../data/src_food/training/6_415.jpg ../data/food-training-sample
cp ../data/src_food/training/6_419.jpg ../data/food-training-sample
cp ../data/src_food/training/6_41.jpg ../data/food-training-sample
cp ../data/src_food/training/6_424.jpg ../data/food-training-sample
cp ../data/src_food/training/6_428.jpg ../data/food-training-sample
cp ../data/src_food/training/6_43.jpg ../data/food-training-sample
cp ../data/src_food/training/6_48.jpg ../data/food-training-sample
cp ../data/src_food/training/6_54.jpg ../data/food-training-sample
cp ../data/src_food/training/6_61.jpg ../data/food-training-sample
cp ../data/src_food/training/6_64.jpg ../data/food-training-sample
cp ../data/src_food/training/6_66.jpg ../data/food-training-sample
cp ../data/src_food/training/6_68.jpg ../data/food-training-sample
cp ../data/src_food/training/6_74.jpg ../data/food-training-sample
cp ../data/src_food/training/6_76.jpg ../data/food-training-sample
cp ../data/src_food/training/6_84.jpg ../data/food-training-sample
cp ../data/src_food/training/6_85.jpg ../data/food-training-sample
cp ../data/src_food/training/6_89.jpg ../data/food-training-sample
cp ../data/src_food/training/6_90.jpg ../data/food-training-sample
cp ../data/src_food/training/6_92.jpg ../data/food-training-sample
cp ../data/src_food/training/7_103.jpg ../data/food-training-sample
cp ../data/src_food/training/7_105.jpg ../data/food-training-sample
cp ../data/src_food/training/7_111.jpg ../data/food-training-sample
cp ../data/src_food/training/7_112.jpg ../data/food-training-sample
cp ../data/src_food/training/7_113.jpg ../data/food-training-sample
cp ../data/src_food/training/7_126.jpg ../data/food-training-sample
cp ../data/src_food/training/7_129.jpg ../data/food-training-sample
cp ../data/src_food/training/7_131.jpg ../data/food-training-sample
cp ../data/src_food/training/7_133.jpg ../data/food-training-sample
cp ../data/src_food/training/7_135.jpg ../data/food-training-sample
cp ../data/src_food/training/7_140.jpg ../data/food-training-sample
cp ../data/src_food/training/7_141.jpg ../data/food-training-sample
cp ../data/src_food/training/7_144.jpg ../data/food-training-sample
cp ../data/src_food/training/7_145.jpg ../data/food-training-sample
cp ../data/src_food/training/7_148.jpg ../data/food-training-sample
cp ../data/src_food/training/7_14.jpg ../data/food-training-sample
cp ../data/src_food/training/7_154.jpg ../data/food-training-sample
cp ../data/src_food/training/7_155.jpg ../data/food-training-sample
cp ../data/src_food/training/7_161.jpg ../data/food-training-sample
cp ../data/src_food/training/7_165.jpg ../data/food-training-sample
cp ../data/src_food/training/7_168.jpg ../data/food-training-sample
cp ../data/src_food/training/7_169.jpg ../data/food-training-sample
cp ../data/src_food/training/7_16.jpg ../data/food-training-sample
cp ../data/src_food/training/7_171.jpg ../data/food-training-sample
cp ../data/src_food/training/7_172.jpg ../data/food-training-sample
cp ../data/src_food/training/7_175.jpg ../data/food-training-sample
cp ../data/src_food/training/7_176.jpg ../data/food-training-sample
cp ../data/src_food/training/7_177.jpg ../data/food-training-sample
cp ../data/src_food/training/7_179.jpg ../data/food-training-sample
cp ../data/src_food/training/7_180.jpg ../data/food-training-sample
cp ../data/src_food/training/7_182.jpg ../data/food-training-sample
cp ../data/src_food/training/7_183.jpg ../data/food-training-sample
cp ../data/src_food/training/7_184.jpg ../data/food-training-sample
cp ../data/src_food/training/7_186.jpg ../data/food-training-sample
cp ../data/src_food/training/7_187.jpg ../data/food-training-sample
cp ../data/src_food/training/7_189.jpg ../data/food-training-sample
cp ../data/src_food/training/7_198.jpg ../data/food-training-sample
cp ../data/src_food/training/7_1.jpg ../data/food-training-sample
cp ../data/src_food/training/7_200.jpg ../data/food-training-sample
cp ../data/src_food/training/7_204.jpg ../data/food-training-sample
cp ../data/src_food/training/7_207.jpg ../data/food-training-sample
cp ../data/src_food/training/7_20.jpg ../data/food-training-sample
cp ../data/src_food/training/7_210.jpg ../data/food-training-sample
cp ../data/src_food/training/7_211.jpg ../data/food-training-sample
cp ../data/src_food/training/7_213.jpg ../data/food-training-sample
cp ../data/src_food/training/7_217.jpg ../data/food-training-sample
cp ../data/src_food/training/7_21.jpg ../data/food-training-sample
cp ../data/src_food/training/7_220.jpg ../data/food-training-sample
cp ../data/src_food/training/7_221.jpg ../data/food-training-sample
cp ../data/src_food/training/7_222.jpg ../data/food-training-sample
cp ../data/src_food/training/7_224.jpg ../data/food-training-sample
cp ../data/src_food/training/7_225.jpg ../data/food-training-sample
cp ../data/src_food/training/7_229.jpg ../data/food-training-sample
cp ../data/src_food/training/7_237.jpg ../data/food-training-sample
cp ../data/src_food/training/7_238.jpg ../data/food-training-sample
cp ../data/src_food/training/7_244.jpg ../data/food-training-sample
cp ../data/src_food/training/7_245.jpg ../data/food-training-sample
cp ../data/src_food/training/7_247.jpg ../data/food-training-sample
cp ../data/src_food/training/7_248.jpg ../data/food-training-sample
cp ../data/src_food/training/7_24.jpg ../data/food-training-sample
cp ../data/src_food/training/7_251.jpg ../data/food-training-sample
cp ../data/src_food/training/7_252.jpg ../data/food-training-sample
cp ../data/src_food/training/7_253.jpg ../data/food-training-sample
cp ../data/src_food/training/7_255.jpg ../data/food-training-sample
cp ../data/src_food/training/7_265.jpg ../data/food-training-sample
cp ../data/src_food/training/7_266.jpg ../data/food-training-sample
cp ../data/src_food/training/7_267.jpg ../data/food-training-sample
cp ../data/src_food/training/7_273.jpg ../data/food-training-sample
cp ../data/src_food/training/7_276.jpg ../data/food-training-sample
cp ../data/src_food/training/7_277.jpg ../data/food-training-sample
cp ../data/src_food/training/7_2.jpg ../data/food-training-sample
cp ../data/src_food/training/7_31.jpg ../data/food-training-sample
cp ../data/src_food/training/7_34.jpg ../data/food-training-sample
cp ../data/src_food/training/7_38.jpg ../data/food-training-sample
cp ../data/src_food/training/7_39.jpg ../data/food-training-sample
cp ../data/src_food/training/7_44.jpg ../data/food-training-sample
cp ../data/src_food/training/7_48.jpg ../data/food-training-sample
cp ../data/src_food/training/7_52.jpg ../data/food-training-sample
cp ../data/src_food/training/7_54.jpg ../data/food-training-sample
cp ../data/src_food/training/7_55.jpg ../data/food-training-sample
cp ../data/src_food/training/7_58.jpg ../data/food-training-sample
cp ../data/src_food/training/7_63.jpg ../data/food-training-sample
cp ../data/src_food/training/7_65.jpg ../data/food-training-sample
cp ../data/src_food/training/7_66.jpg ../data/food-training-sample
cp ../data/src_food/training/7_67.jpg ../data/food-training-sample
cp ../data/src_food/training/7_71.jpg ../data/food-training-sample
cp ../data/src_food/training/7_72.jpg ../data/food-training-sample
cp ../data/src_food/training/7_74.jpg ../data/food-training-sample
cp ../data/src_food/training/7_78.jpg ../data/food-training-sample
cp ../data/src_food/training/7_81.jpg ../data/food-training-sample
cp ../data/src_food/training/7_89.jpg ../data/food-training-sample
cp ../data/src_food/training/7_8.jpg ../data/food-training-sample
cp ../data/src_food/training/7_91.jpg ../data/food-training-sample
cp ../data/src_food/training/7_93.jpg ../data/food-training-sample
cp ../data/src_food/training/7_94.jpg ../data/food-training-sample
cp ../data/src_food/training/7_95.jpg ../data/food-training-sample
cp ../data/src_food/training/7_96.jpg ../data/food-training-sample
cp ../data/src_food/training/7_98.jpg ../data/food-training-sample
cp ../data/src_food/training/7_99.jpg ../data/food-training-sample
cp ../data/src_food/training/7_9.jpg ../data/food-training-sample
cp ../data/src_food/training/8_126.jpg ../data/food-training-sample
cp ../data/src_food/training/8_127.jpg ../data/food-training-sample
cp ../data/src_food/training/8_137.jpg ../data/food-training-sample
cp ../data/src_food/training/8_13.jpg ../data/food-training-sample
cp ../data/src_food/training/8_141.jpg ../data/food-training-sample
cp ../data/src_food/training/8_152.jpg ../data/food-training-sample
cp ../data/src_food/training/8_195.jpg ../data/food-training-sample
cp ../data/src_food/training/8_199.jpg ../data/food-training-sample
cp ../data/src_food/training/8_1.jpg ../data/food-training-sample
cp ../data/src_food/training/8_203.jpg ../data/food-training-sample
cp ../data/src_food/training/8_219.jpg ../data/food-training-sample
cp ../data/src_food/training/8_220.jpg ../data/food-training-sample
cp ../data/src_food/training/8_229.jpg ../data/food-training-sample
cp ../data/src_food/training/8_232.jpg ../data/food-training-sample
cp ../data/src_food/training/8_23.jpg ../data/food-training-sample
cp ../data/src_food/training/8_244.jpg ../data/food-training-sample
cp ../data/src_food/training/8_246.jpg ../data/food-training-sample
cp ../data/src_food/training/8_24.jpg ../data/food-training-sample
cp ../data/src_food/training/8_253.jpg ../data/food-training-sample
cp ../data/src_food/training/8_255.jpg ../data/food-training-sample
cp ../data/src_food/training/8_266.jpg ../data/food-training-sample
cp ../data/src_food/training/8_271.jpg ../data/food-training-sample
cp ../data/src_food/training/8_27.jpg ../data/food-training-sample
cp ../data/src_food/training/8_282.jpg ../data/food-training-sample
cp ../data/src_food/training/8_284.jpg ../data/food-training-sample
cp ../data/src_food/training/8_286.jpg ../data/food-training-sample
cp ../data/src_food/training/8_296.jpg ../data/food-training-sample
cp ../data/src_food/training/8_303.jpg ../data/food-training-sample
cp ../data/src_food/training/8_315.jpg ../data/food-training-sample
cp ../data/src_food/training/8_318.jpg ../data/food-training-sample
cp ../data/src_food/training/8_320.jpg ../data/food-training-sample
cp ../data/src_food/training/8_328.jpg ../data/food-training-sample
cp ../data/src_food/training/8_330.jpg ../data/food-training-sample
cp ../data/src_food/training/8_343.jpg ../data/food-training-sample
cp ../data/src_food/training/8_357.jpg ../data/food-training-sample
cp ../data/src_food/training/8_359.jpg ../data/food-training-sample
cp ../data/src_food/training/8_366.jpg ../data/food-training-sample
cp ../data/src_food/training/8_368.jpg ../data/food-training-sample
cp ../data/src_food/training/8_374.jpg ../data/food-training-sample
cp ../data/src_food/training/8_376.jpg ../data/food-training-sample
cp ../data/src_food/training/8_383.jpg ../data/food-training-sample
cp ../data/src_food/training/8_388.jpg ../data/food-training-sample
cp ../data/src_food/training/8_389.jpg ../data/food-training-sample
cp ../data/src_food/training/8_401.jpg ../data/food-training-sample
cp ../data/src_food/training/8_403.jpg ../data/food-training-sample
cp ../data/src_food/training/8_410.jpg ../data/food-training-sample
cp ../data/src_food/training/8_426.jpg ../data/food-training-sample
cp ../data/src_food/training/8_445.jpg ../data/food-training-sample
cp ../data/src_food/training/8_447.jpg ../data/food-training-sample
cp ../data/src_food/training/8_461.jpg ../data/food-training-sample
cp ../data/src_food/training/8_477.jpg ../data/food-training-sample
cp ../data/src_food/training/8_485.jpg ../data/food-training-sample
cp ../data/src_food/training/8_48.jpg ../data/food-training-sample
cp ../data/src_food/training/8_4.jpg ../data/food-training-sample
cp ../data/src_food/training/8_503.jpg ../data/food-training-sample
cp ../data/src_food/training/8_506.jpg ../data/food-training-sample
cp ../data/src_food/training/8_50.jpg ../data/food-training-sample
cp ../data/src_food/training/8_51.jpg ../data/food-training-sample
cp ../data/src_food/training/8_533.jpg ../data/food-training-sample
cp ../data/src_food/training/8_534.jpg ../data/food-training-sample
cp ../data/src_food/training/8_545.jpg ../data/food-training-sample
cp ../data/src_food/training/8_564.jpg ../data/food-training-sample
cp ../data/src_food/training/8_57.jpg ../data/food-training-sample
cp ../data/src_food/training/8_602.jpg ../data/food-training-sample
cp ../data/src_food/training/8_615.jpg ../data/food-training-sample
cp ../data/src_food/training/8_629.jpg ../data/food-training-sample
cp ../data/src_food/training/8_630.jpg ../data/food-training-sample
cp ../data/src_food/training/8_631.jpg ../data/food-training-sample
cp ../data/src_food/training/8_633.jpg ../data/food-training-sample
cp ../data/src_food/training/8_641.jpg ../data/food-training-sample
cp ../data/src_food/training/8_644.jpg ../data/food-training-sample
cp ../data/src_food/training/8_647.jpg ../data/food-training-sample
cp ../data/src_food/training/8_648.jpg ../data/food-training-sample
cp ../data/src_food/training/8_649.jpg ../data/food-training-sample
cp ../data/src_food/training/8_657.jpg ../data/food-training-sample
cp ../data/src_food/training/8_667.jpg ../data/food-training-sample
cp ../data/src_food/training/8_680.jpg ../data/food-training-sample
cp ../data/src_food/training/8_684.jpg ../data/food-training-sample
cp ../data/src_food/training/8_686.jpg ../data/food-training-sample
cp ../data/src_food/training/8_687.jpg ../data/food-training-sample
cp ../data/src_food/training/8_68.jpg ../data/food-training-sample
cp ../data/src_food/training/8_694.jpg ../data/food-training-sample
cp ../data/src_food/training/8_701.jpg ../data/food-training-sample
cp ../data/src_food/training/8_707.jpg ../data/food-training-sample
cp ../data/src_food/training/8_708.jpg ../data/food-training-sample
cp ../data/src_food/training/8_709.jpg ../data/food-training-sample
cp ../data/src_food/training/8_716.jpg ../data/food-training-sample
cp ../data/src_food/training/8_725.jpg ../data/food-training-sample
cp ../data/src_food/training/8_739.jpg ../data/food-training-sample
cp ../data/src_food/training/8_750.jpg ../data/food-training-sample
cp ../data/src_food/training/8_778.jpg ../data/food-training-sample
cp ../data/src_food/training/8_786.jpg ../data/food-training-sample
cp ../data/src_food/training/8_790.jpg ../data/food-training-sample
cp ../data/src_food/training/8_796.jpg ../data/food-training-sample
cp ../data/src_food/training/8_802.jpg ../data/food-training-sample
cp ../data/src_food/training/8_817.jpg ../data/food-training-sample
cp ../data/src_food/training/8_825.jpg ../data/food-training-sample
cp ../data/src_food/training/8_843.jpg ../data/food-training-sample
cp ../data/src_food/training/8_846.jpg ../data/food-training-sample
cp ../data/src_food/training/8_8.jpg ../data/food-training-sample
cp ../data/src_food/training/9_1007.jpg ../data/food-training-sample
cp ../data/src_food/training/9_1011.jpg ../data/food-training-sample
cp ../data/src_food/training/9_1058.jpg ../data/food-training-sample
cp ../data/src_food/training/9_1068.jpg ../data/food-training-sample
cp ../data/src_food/training/9_1100.jpg ../data/food-training-sample
cp ../data/src_food/training/9_113.jpg ../data/food-training-sample
cp ../data/src_food/training/9_1164.jpg ../data/food-training-sample
cp ../data/src_food/training/9_1223.jpg ../data/food-training-sample
cp ../data/src_food/training/9_1225.jpg ../data/food-training-sample
cp ../data/src_food/training/9_1236.jpg ../data/food-training-sample
cp ../data/src_food/training/9_1255.jpg ../data/food-training-sample
cp ../data/src_food/training/9_1258.jpg ../data/food-training-sample
cp ../data/src_food/training/9_1280.jpg ../data/food-training-sample
cp ../data/src_food/training/9_1282.jpg ../data/food-training-sample
cp ../data/src_food/training/9_1290.jpg ../data/food-training-sample
cp ../data/src_food/training/9_1293.jpg ../data/food-training-sample
cp ../data/src_food/training/9_130.jpg ../data/food-training-sample
cp ../data/src_food/training/9_1317.jpg ../data/food-training-sample
cp ../data/src_food/training/9_1321.jpg ../data/food-training-sample
cp ../data/src_food/training/9_1327.jpg ../data/food-training-sample
cp ../data/src_food/training/9_1394.jpg ../data/food-training-sample
cp ../data/src_food/training/9_1399.jpg ../data/food-training-sample
cp ../data/src_food/training/9_1400.jpg ../data/food-training-sample
cp ../data/src_food/training/9_1402.jpg ../data/food-training-sample
cp ../data/src_food/training/9_1405.jpg ../data/food-training-sample
cp ../data/src_food/training/9_1409.jpg ../data/food-training-sample
cp ../data/src_food/training/9_140.jpg ../data/food-training-sample
cp ../data/src_food/training/9_1431.jpg ../data/food-training-sample
cp ../data/src_food/training/9_1436.jpg ../data/food-training-sample
cp ../data/src_food/training/9_1486.jpg ../data/food-training-sample
cp ../data/src_food/training/9_173.jpg ../data/food-training-sample
cp ../data/src_food/training/9_197.jpg ../data/food-training-sample
cp ../data/src_food/training/9_203.jpg ../data/food-training-sample
cp ../data/src_food/training/9_222.jpg ../data/food-training-sample
cp ../data/src_food/training/9_231.jpg ../data/food-training-sample
cp ../data/src_food/training/9_236.jpg ../data/food-training-sample
cp ../data/src_food/training/9_25.jpg ../data/food-training-sample
cp ../data/src_food/training/9_282.jpg ../data/food-training-sample
cp ../data/src_food/training/9_288.jpg ../data/food-training-sample
cp ../data/src_food/training/9_289.jpg ../data/food-training-sample
cp ../data/src_food/training/9_304.jpg ../data/food-training-sample
cp ../data/src_food/training/9_338.jpg ../data/food-training-sample
cp ../data/src_food/training/9_345.jpg ../data/food-training-sample
cp ../data/src_food/training/9_388.jpg ../data/food-training-sample
cp ../data/src_food/training/9_390.jpg ../data/food-training-sample
cp ../data/src_food/training/9_406.jpg ../data/food-training-sample
cp ../data/src_food/training/9_409.jpg ../data/food-training-sample
cp ../data/src_food/training/9_410.jpg ../data/food-training-sample
cp ../data/src_food/training/9_415.jpg ../data/food-training-sample
cp ../data/src_food/training/9_428.jpg ../data/food-training-sample
cp ../data/src_food/training/9_439.jpg ../data/food-training-sample
cp ../data/src_food/training/9_444.jpg ../data/food-training-sample
cp ../data/src_food/training/9_459.jpg ../data/food-training-sample
cp ../data/src_food/training/9_461.jpg ../data/food-training-sample
cp ../data/src_food/training/9_464.jpg ../data/food-training-sample
cp ../data/src_food/training/9_482.jpg ../data/food-training-sample
cp ../data/src_food/training/9_510.jpg ../data/food-training-sample
cp ../data/src_food/training/9_524.jpg ../data/food-training-sample
cp ../data/src_food/training/9_52.jpg ../data/food-training-sample
cp ../data/src_food/training/9_533.jpg ../data/food-training-sample
cp ../data/src_food/training/9_542.jpg ../data/food-training-sample
cp ../data/src_food/training/9_552.jpg ../data/food-training-sample
cp ../data/src_food/training/9_565.jpg ../data/food-training-sample
cp ../data/src_food/training/9_56.jpg ../data/food-training-sample
cp ../data/src_food/training/9_594.jpg ../data/food-training-sample
cp ../data/src_food/training/9_598.jpg ../data/food-training-sample
cp ../data/src_food/training/9_604.jpg ../data/food-training-sample
cp ../data/src_food/training/9_606.jpg ../data/food-training-sample
cp ../data/src_food/training/9_607.jpg ../data/food-training-sample
cp ../data/src_food/training/9_631.jpg ../data/food-training-sample
cp ../data/src_food/training/9_633.jpg ../data/food-training-sample
cp ../data/src_food/training/9_637.jpg ../data/food-training-sample
cp ../data/src_food/training/9_639.jpg ../data/food-training-sample
cp ../data/src_food/training/9_645.jpg ../data/food-training-sample
cp ../data/src_food/training/9_654.jpg ../data/food-training-sample
cp ../data/src_food/training/9_658.jpg ../data/food-training-sample
cp ../data/src_food/training/9_695.jpg ../data/food-training-sample
cp ../data/src_food/training/9_698.jpg ../data/food-training-sample
cp ../data/src_food/training/9_735.jpg ../data/food-training-sample
cp ../data/src_food/training/9_740.jpg ../data/food-training-sample
cp ../data/src_food/training/9_741.jpg ../data/food-training-sample
cp ../data/src_food/training/9_74.jpg ../data/food-training-sample
cp ../data/src_food/training/9_761.jpg ../data/food-training-sample
cp ../data/src_food/training/9_76.jpg ../data/food-training-sample
cp ../data/src_food/training/9_801.jpg ../data/food-training-sample
cp ../data/src_food/training/9_822.jpg ../data/food-training-sample
cp ../data/src_food/training/9_828.jpg ../data/food-training-sample
cp ../data/src_food/training/9_859.jpg ../data/food-training-sample
cp ../data/src_food/training/9_87.jpg ../data/food-training-sample
cp ../data/src_food/training/9_882.jpg ../data/food-training-sample
cp ../data/src_food/training/9_897.jpg ../data/food-training-sample
cp ../data/src_food/training/9_89.jpg ../data/food-training-sample
cp ../data/src_food/training/9_912.jpg ../data/food-training-sample
cp ../data/src_food/training/9_918.jpg ../data/food-training-sample
cp ../data/src_food/training/9_919.jpg ../data/food-training-sample
cp ../data/src_food/training/9_925.jpg ../data/food-training-sample
cp ../data/src_food/training/9_927.jpg ../data/food-training-sample
cp ../data/src_food/training/9_954.jpg ../data/food-training-sample
cp ../data/src_food/training/9_955.jpg ../data/food-training-sample
cp ../data/src_food/training/9_969.jpg ../data/food-training-sample
cp ../data/src_food/training/10_105.jpg ../data/food-training-sample
cp ../data/src_food/training/10_121.jpg ../data/food-training-sample
cp ../data/src_food/training/10_131.jpg ../data/food-training-sample
cp ../data/src_food/training/10_141.jpg ../data/food-training-sample
cp ../data/src_food/training/10_145.jpg ../data/food-training-sample
cp ../data/src_food/training/10_148.jpg ../data/food-training-sample
cp ../data/src_food/training/10_149.jpg ../data/food-training-sample
cp ../data/src_food/training/10_153.jpg ../data/food-training-sample
cp ../data/src_food/training/10_156.jpg ../data/food-training-sample
cp ../data/src_food/training/10_177.jpg ../data/food-training-sample
cp ../data/src_food/training/10_185.jpg ../data/food-training-sample
cp ../data/src_food/training/10_193.jpg ../data/food-training-sample
cp ../data/src_food/training/10_195.jpg ../data/food-training-sample
cp ../data/src_food/training/10_198.jpg ../data/food-training-sample
cp ../data/src_food/training/10_199.jpg ../data/food-training-sample
cp ../data/src_food/training/10_208.jpg ../data/food-training-sample
cp ../data/src_food/training/10_20.jpg ../data/food-training-sample
cp ../data/src_food/training/10_215.jpg ../data/food-training-sample
cp ../data/src_food/training/10_229.jpg ../data/food-training-sample
cp ../data/src_food/training/10_245.jpg ../data/food-training-sample
cp ../data/src_food/training/10_249.jpg ../data/food-training-sample
cp ../data/src_food/training/10_24.jpg ../data/food-training-sample
cp ../data/src_food/training/10_256.jpg ../data/food-training-sample
cp ../data/src_food/training/10_257.jpg ../data/food-training-sample
cp ../data/src_food/training/10_259.jpg ../data/food-training-sample
cp ../data/src_food/training/10_270.jpg ../data/food-training-sample
cp ../data/src_food/training/10_27.jpg ../data/food-training-sample
cp ../data/src_food/training/10_287.jpg ../data/food-training-sample
cp ../data/src_food/training/10_288.jpg ../data/food-training-sample
cp ../data/src_food/training/10_295.jpg ../data/food-training-sample
cp ../data/src_food/training/10_2.jpg ../data/food-training-sample
cp ../data/src_food/training/10_310.jpg ../data/food-training-sample
cp ../data/src_food/training/10_314.jpg ../data/food-training-sample
cp ../data/src_food/training/10_315.jpg ../data/food-training-sample
cp ../data/src_food/training/10_318.jpg ../data/food-training-sample
cp ../data/src_food/training/10_321.jpg ../data/food-training-sample
cp ../data/src_food/training/10_324.jpg ../data/food-training-sample
cp ../data/src_food/training/10_325.jpg ../data/food-training-sample
cp ../data/src_food/training/10_33.jpg ../data/food-training-sample
cp ../data/src_food/training/10_345.jpg ../data/food-training-sample
cp ../data/src_food/training/10_34.jpg ../data/food-training-sample
cp ../data/src_food/training/10_360.jpg ../data/food-training-sample
cp ../data/src_food/training/10_370.jpg ../data/food-training-sample
cp ../data/src_food/training/10_374.jpg ../data/food-training-sample
cp ../data/src_food/training/10_376.jpg ../data/food-training-sample
cp ../data/src_food/training/10_380.jpg ../data/food-training-sample
cp ../data/src_food/training/10_381.jpg ../data/food-training-sample
cp ../data/src_food/training/10_399.jpg ../data/food-training-sample
cp ../data/src_food/training/10_40.jpg ../data/food-training-sample
cp ../data/src_food/training/10_428.jpg ../data/food-training-sample
cp ../data/src_food/training/10_429.jpg ../data/food-training-sample
cp ../data/src_food/training/10_441.jpg ../data/food-training-sample
cp ../data/src_food/training/10_442.jpg ../data/food-training-sample
cp ../data/src_food/training/10_443.jpg ../data/food-training-sample
cp ../data/src_food/training/10_447.jpg ../data/food-training-sample
cp ../data/src_food/training/10_449.jpg ../data/food-training-sample
cp ../data/src_food/training/10_44.jpg ../data/food-training-sample
cp ../data/src_food/training/10_457.jpg ../data/food-training-sample
cp ../data/src_food/training/10_459.jpg ../data/food-training-sample
cp ../data/src_food/training/10_466.jpg ../data/food-training-sample
cp ../data/src_food/training/10_470.jpg ../data/food-training-sample
cp ../data/src_food/training/10_484.jpg ../data/food-training-sample
cp ../data/src_food/training/10_486.jpg ../data/food-training-sample
cp ../data/src_food/training/10_487.jpg ../data/food-training-sample
cp ../data/src_food/training/10_488.jpg ../data/food-training-sample
cp ../data/src_food/training/10_493.jpg ../data/food-training-sample
cp ../data/src_food/training/10_497.jpg ../data/food-training-sample
cp ../data/src_food/training/10_49.jpg ../data/food-training-sample
cp ../data/src_food/training/10_534.jpg ../data/food-training-sample
cp ../data/src_food/training/10_538.jpg ../data/food-training-sample
cp ../data/src_food/training/10_548.jpg ../data/food-training-sample
cp ../data/src_food/training/10_553.jpg ../data/food-training-sample
cp ../data/src_food/training/10_561.jpg ../data/food-training-sample
cp ../data/src_food/training/10_566.jpg ../data/food-training-sample
cp ../data/src_food/training/10_573.jpg ../data/food-training-sample
cp ../data/src_food/training/10_576.jpg ../data/food-training-sample
cp ../data/src_food/training/10_578.jpg ../data/food-training-sample
cp ../data/src_food/training/10_588.jpg ../data/food-training-sample
cp ../data/src_food/training/10_58.jpg ../data/food-training-sample
cp ../data/src_food/training/10_596.jpg ../data/food-training-sample
cp ../data/src_food/training/10_607.jpg ../data/food-training-sample
cp ../data/src_food/training/10_611.jpg ../data/food-training-sample
cp ../data/src_food/training/10_617.jpg ../data/food-training-sample
cp ../data/src_food/training/10_624.jpg ../data/food-training-sample
cp ../data/src_food/training/10_642.jpg ../data/food-training-sample
cp ../data/src_food/training/10_646.jpg ../data/food-training-sample
cp ../data/src_food/training/10_64.jpg ../data/food-training-sample
cp ../data/src_food/training/10_651.jpg ../data/food-training-sample
cp ../data/src_food/training/10_653.jpg ../data/food-training-sample
cp ../data/src_food/training/10_657.jpg ../data/food-training-sample
cp ../data/src_food/training/10_661.jpg ../data/food-training-sample
cp ../data/src_food/training/10_666.jpg ../data/food-training-sample
cp ../data/src_food/training/10_667.jpg ../data/food-training-sample
cp ../data/src_food/training/10_681.jpg ../data/food-training-sample
cp ../data/src_food/training/10_699.jpg ../data/food-training-sample
cp ../data/src_food/training/10_78.jpg ../data/food-training-sample
cp ../data/src_food/training/10_88.jpg ../data/food-training-sample
cp ../data/src_food/training/10_90.jpg ../data/food-training-sample
cp ../data/src_food/training/10_91.jpg ../data/food-training-sample
cp ../data/src_food/training/10_96.jpg ../data/food-training-sample
